#!/bin/bash

# Where libs to link against are kept
SHARED_LIB=Shared_V4/lib

MAJOR=4
MINOR=10

LIB_SUFFIX=.dylib.${MAJOR}.${MINOR}

if [[ ! -e ${SHARED_LIB} ]]; then
   mkdir ${SHARED_LIB}
fi

# Collect DLLs that are produced as part of USBDM
cp "wxPlugin_DLL/usbdm-wxPlugin/"*.dylib.*                  ${SHARED_LIB}
cp "USBDM_DLL/usbdm/"*.dylib.*                              ${SHARED_LIB}
cp "USBDM_DLL/usbdm-debug/"*.dylib.*                        ${SHARED_LIB}
cp "USBDM_DSC_DLL/usbdm-dsc/"*.dylib.*                      ${SHARED_LIB}
cp "USBDM_DSC_DLL/usbdm-dsc-debug/"*.dylib.*                ${SHARED_LIB}
cp "Usbdm_TCL/usbdm-tcl/"*.dylib.*                          ${SHARED_LIB}
cp "Usbdm_TCL/usbdm-tcl-debug/"*.dylib.*                    ${SHARED_LIB}

SHARED_LIBS="libusbdm-wxPlugin libusbdm-wxStub libusbdm libusbdm-debug libusbdm-dsc libusbdm-dsc-debug libusbdm-tcl libusbdm-tcl-debug"
for FILE in ${SHARED_LIBS}; do
   if [[ -e Shared_V4/lib/${FILE}.dylib.${MAJOR}.${MINOR} ]]; then
      if [[ ! -e ${SHARED_LIB}/${FILE}.dylib.${MAJOR} ]]; then
         ln -s ${FILE}.dylib.${MAJOR}.${MINOR}    ${SHARED_LIB}/${FILE}.dylib.${MAJOR}
      fi
      if [[ ! -e ${SHARED_LIB}/${FILE}.dylib ]]; then
         ln -s ${FILE}.dylib.${MAJOR}.${MINOR}    ${SHARED_LIB}/${FILE}.dylib
      fi
   fi
done

